"""Models for Earnings, Dividends, and ROI Tracking"""

from pydantic import BaseModel, Field, ConfigDict
from typing import Optional, Dict, Any, List
from datetime import datetime, timezone
import uuid

class DividendDistribution(BaseModel):
    """Dividend payment to token holder"""
    model_config = ConfigDict(extra="ignore")
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    token_id: str
    asset_id: str
    user_id: str  # Recipient
    amount: float  # Dividend amount in USD
    tokens_held: int  # Number of tokens held at distribution time
    distribution_date: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    period: str  # "2024-01", "2024-Q1", etc.
    status: str = "pending"  # pending, completed, failed
    transaction_hash: Optional[str] = None
    metadata: Dict[str, Any] = {}

class AssetRevenue(BaseModel):
    """Revenue generated by an asset (rent, sales, etc.)"""
    model_config = ConfigDict(extra="ignore")
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    asset_id: str
    amount: float  # Revenue in USD
    revenue_type: str  # "rent", "sale", "interest", "other"
    description: str
    date: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: Dict[str, Any] = {}

class PortfolioHolding(BaseModel):
    """User's token holdings and performance"""
    model_config = ConfigDict(extra="ignore")
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    user_id: str
    token_id: str
    asset_id: str
    quantity: int
    purchase_price_per_token: float
    total_invested: float
    current_value: float
    total_dividends_received: float = 0.0
    roi_percentage: float = 0.0
    acquisition_date: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    last_updated: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class AssetPerformance(BaseModel):
    """Performance metrics for an asset"""
    model_config = ConfigDict(extra="ignore")
    asset_id: str
    total_revenue: float = 0.0
    total_dividends_paid: float = 0.0
    total_investors: int = 0
    average_roi: float = 0.0
    last_dividend_date: Optional[datetime] = None
    performance_score: float = 0.0  # 0-100
    metadata: Dict[str, Any] = {}

class DividendConfig(BaseModel):
    """Configuration for dividend distributions"""
    model_config = ConfigDict(extra="ignore")
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    asset_id: str
    frequency: str = "monthly"  # monthly, quarterly, annual
    distribution_percentage: float = 0.80  # 80% of revenue to holders, 20% to platform
    auto_distribute: bool = True
    min_distribution_amount: float = 10.0  # Minimum $10 to distribute
    next_distribution_date: Optional[datetime] = None
    metadata: Dict[str, Any] = {}
